
server:
  port: 8761
spring:
  application:
    name: eureka-micros
  config:
    import: optional:configserver:http//localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultzone: http://localhost:8761:&{server.port}/eureka/

