server:
  port: 8761
spring:
  application:
    name: eureka-micros

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultzone: http://localhost:8761:&{server.port}/eureka/


