
server:
  port: 8090

spring:
  application:
    name: login-micros
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/loginDB
    username: postgres
    password: alucard2107
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

